export interface ContactSubmission {
  id: string;
  name: string;
  email: string;
  subject: string;
  message: string;
  status: "unread" | "read" | "replied";
  createdAt: string;
  updatedAt: string;
}

export const mockContactSubmissions: ContactSubmission[] = [
  {
    id: "1",
    name: "Andi Pratama",
    email: "andi@example.com",
    subject: "Product Inquiry",
    message: "Hi, I'm interested in your premium plan. Could you provide more details about the features included?",
    status: "unread",
    createdAt: "2025-04-01T08:00:00Z",
    updatedAt: "2025-04-01T08:00:00Z",
  },
  {
    id: "2",
    name: "Siti Rahayu",
    email: "siti.rahayu@example.com",
    subject: "Partnership Opportunity",
    message: "We would like to discuss a potential partnership between our companies. Please let me know when you're available for a call.",
    status: "read",
    createdAt: "2025-04-02T10:30:00Z",
    updatedAt: "2025-04-02T11:00:00Z",
  },
  {
    id: "3",
    name: "Budi Santoso",
    email: "budi.s@example.com",
    subject: "Technical Support",
    message: "I'm experiencing issues with the checkout process. The payment button is not responding on my end.",
    status: "replied",
    createdAt: "2025-04-03T14:00:00Z",
    updatedAt: "2025-04-04T09:00:00Z",
  },
  {
    id: "4",
    name: "Dewi Lestari",
    email: "dewi.lestari@example.com",
    subject: "Bulk Order Request",
    message: "We need 500 units of your product for our company event. Do you offer bulk discounts?",
    status: "unread",
    createdAt: "2025-04-05T09:15:00Z",
    updatedAt: "2025-04-05T09:15:00Z",
  },
  {
    id: "5",
    name: "Rizky Hidayat",
    email: "rizky.h@example.com",
    subject: "Feedback and Suggestions",
    message: "Love your product! One suggestion: it would be great to have a dark mode option in the dashboard.",
    status: "read",
    createdAt: "2025-04-06T16:00:00Z",
    updatedAt: "2025-04-06T16:30:00Z",
  },
  {
    id: "6",
    name: "Maya Putri",
    email: "maya.putri@example.com",
    subject: "Refund Request",
    message: "I accidentally purchased the wrong plan. Is it possible to get a refund and switch to the correct one?",
    status: "replied",
    createdAt: "2025-04-07T11:00:00Z",
    updatedAt: "2025-04-08T10:00:00Z",
  },
  {
    id: "7",
    name: "Fajar Nugroho",
    email: "fajar.n@example.com",
    subject: "Integration Question",
    message: "Does your platform support integration with Salesforce? We're evaluating options for our sales team.",
    status: "unread",
    createdAt: "2025-04-09T08:30:00Z",
    updatedAt: "2025-04-09T08:30:00Z",
  },
  {
    id: "8",
    name: "Nadia Sari",
    email: "nadia.sari@example.com",
    subject: "Account Issue",
    message: "I can't log into my account after the recent password reset. I've tried multiple browsers with the same result.",
    status: "read",
    createdAt: "2025-04-10T13:45:00Z",
    updatedAt: "2025-04-10T14:00:00Z",
  },
  {
    id: "9",
    name: "Hendra Wijaya",
    email: "hendra.w@example.com",
    subject: "Media Inquiry",
    message: "I'm a journalist writing an article about innovative tech startups. Would you be available for an interview?",
    status: "unread",
    createdAt: "2025-04-11T09:00:00Z",
    updatedAt: "2025-04-11T09:00:00Z",
  },
  {
    id: "10",
    name: "Lina Kusuma",
    email: "lina.k@example.com",
    subject: "Feature Request",
    message: "It would be really helpful to have an export-to-PDF feature for reports. Is this on your roadmap?",
    status: "replied",
    createdAt: "2025-04-12T15:00:00Z",
    updatedAt: "2025-04-13T11:00:00Z",
  },
  {
    id: "11",
    name: "Agus Setiawan",
    email: "agus.setiawan@example.com",
    subject: "Billing Discrepancy",
    message: "I was charged twice for my monthly subscription. Could you please check my account and issue a refund for the duplicate charge?",
    status: "unread",
    createdAt: "2025-04-14T07:30:00Z",
    updatedAt: "2025-04-14T07:30:00Z",
  },
  {
    id: "12",
    name: "Rina Marlina",
    email: "rina.m@example.com",
    subject: "Training Inquiry",
    message: "Do you offer training sessions for new users? Our team just onboarded and we'd like to get the most out of the platform.",
    status: "read",
    createdAt: "2025-04-15T10:00:00Z",
    updatedAt: "2025-04-15T10:30:00Z",
  },
  {
    id: "13",
    name: "Taufik Hidayat",
    email: "taufik.h@example.com",
    subject: "API Rate Limit",
    message: "We're hitting the API rate limit frequently. Is there an enterprise plan with higher limits available?",
    status: "unread",
    createdAt: "2025-04-16T14:00:00Z",
    updatedAt: "2025-04-16T14:00:00Z",
  },
  {
    id: "14",
    name: "Putri Ayu",
    email: "putri.ayu@example.com",
    subject: "General Inquiry",
    message: "Just checking if you have any planned webinars or events in the coming months?",
    status: "replied",
    createdAt: "2025-04-17T09:30:00Z",
    updatedAt: "2025-04-18T08:00:00Z",
  },
  {
    id: "15",
    name: "Dian Purnama",
    email: "dian.p@example.com",
    subject: "Bug Report",
    message: "Found a bug: when exporting data with special characters, the CSV file gets corrupted. Steps to reproduce attached.",
    status: "read",
    createdAt: "2025-04-18T16:00:00Z",
    updatedAt: "2025-04-18T16:30:00Z",
  },
];
